### ISSUE TITLE
"Start Maestral on login" doesn't work in 1.9.6 and GUI 1.9.8

### ISSUE THREAD

**Issue by nalim** [samschott/maestral#1147]
**Describe the bug**
After upgrading from 1.9.5 and GUI 1.9.5 to 1.9.6 and GUI 1.9.8 Maestral autostart no longer works. When I run the autostart code from cli:

```
~/.local/bin/maestral_qt --config-name maestral
Traceback (most recent call last):
  File "/home/votava/.local/bin/maestral_qt", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/votava/.local/lib/python3.14/site-packages/maestral_qt/__main__.py", line 20, in main
    run(parsed_args.config_name)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: run() missing 1 required positional argument: 'start_result'
```

In ~/.local/lib/python3.14/site-packages/maestral_qt/\_\_main\_\_.py the run() is called with just one param:

```
run(parsed_args.config_name)
```

but run() in ~/.local/lib/python3.14/site-packages/maestral_qt/main.py expects two params:

```
def run(config_name, start_result: Start):
```

**To Reproduce**
upgrade to 1.9.6, GUI 1.9.8 from 1.9.5

```
python3 -m pip install --upgrade --user maestral[gui]
```

**Expected behaviour**
Maestral (and GUI) should auto start after login

**System:**
 - Maestral version: 1.9.6, GUI 1.9.8
 - Python version: 3.14.2
 - OS: Fedora 43 Workstation x86_64
 - Desktop environment: cinnamon-6.4.12-3.fc43.x86_64
 - PyQt version (for Linux GUI): 5.15.12.dev2507081429

**Additional context**

**Comment by e3m3** [comment]
> **System:**
> 
>     * Maestral version: 1.9.6, GUI 1.9.8
> 
>     * Python version: 3.14.2
> 
>     * OS: Fedora 43 Workstation x86_64
> 
>     * Desktop environment: cinnamon-6.4.12-3.fc43.x86_64
> 
>     * PyQt version (for Linux GUI): 5.15.12.dev2507081429

Thanks @nalim for creating this issue. Confirmed same issue:
*   Python version: 3.14.2
*   OS: Fedora 43 (Kinoite and Sway Atomic)
*   Maestral version: 1.9.6, GUI 1.9.8
*   Installed via pip as above.

To get going right away, feel free to manually apply the 4-line hotfix from the mentioned pull request directly to your installation at `~/.local/lib/python3.14/site-packages/maestral{,_qt}` (which resolved the issue on both of my installations):
*   https://github.com/samschott/maestral-qt/pull/34/changes
*  https://github.com/samschott/maestral/pull/1148/changes
